const HTTP_STATUS = require('http-status');

const DATA_NOT_FOUND = new Error('DATA_NOT_FOUND');
DATA_NOT_FOUND.errCode = 'DATA_NOT_FOUND';
DATA_NOT_FOUND.status = HTTP_STATUS.NOT_FOUND;

const INTERNAL_SERVER_ERROR = new Error('INTERNAL_SERVER_ERROR');
INTERNAL_SERVER_ERROR.errCode = 'INTERNAL_SERVER_ERROR';
INTERNAL_SERVER_ERROR.status = HTTP_STATUS.INTERNAL_SERVER_ERROR;

const BAD_REQUEST = new Error('BAD_REQUEST');
BAD_REQUEST.errCode = 'BAD_REQUEST';
BAD_REQUEST.status = HTTP_STATUS.BAD_REQUEST;

const UNAUTHORIZED = new Error('UNAUTHORIZED');
UNAUTHORIZED.errCode = 'UNAUTHORIZED';
UNAUTHORIZED.status = HTTP_STATUS.UNAUTHORIZED;

const FORBIDDEN = new Error('FORBIDDEN');
FORBIDDEN.errCode = 'FORBIDDEN';
FORBIDDEN.status = HTTP_STATUS.FORBIDDEN;

const CONFLICT = new Error('CONFLICT');
CONFLICT.errCode = 'CONFLICT';
CONFLICT.status = HTTP_STATUS.CONFLICT;

module.exports = {
    HTTP_STATUS,
    DATA_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST,
    UNAUTHORIZED,
    CONFLICT,
    FORBIDDEN,
};
